version: "2.4"

services:
    app:
        build:
            context: .
        environment:
            FLASK_DEBUG: ${FLASK_DEBUG:-0}
            ENVIRONMENT: production
        env_file:
            - .env
        container_name: "tvshow-manager"
        image: "tvshow-manager:latest"
        restart: unless-stopped
        volumes:
            - "./db:/home/app/screentracker/db"
        ports:
            - ${PORT:-1234}:1234
